### ISSUE TITLE
Question for domain classify method

### ISSUE THREAD

**Issue by Shuaiyicao** [pchaigno/dga-collection#4]
Hi, may I have a question? I find couldUseDomain method in README say can classify domain. But when I read the method in codes, I find they only classify by endwith() method. 
```python
def couldUseDomain(self, domain):
    if not domain.endswith('.ddns.net'):
      return False
    label = domain.split('.', 1)[0]
    if 'j' in label or 'y' in label or 'z' in label:
      return False
    return not any(char.isdigit() for char in domain)
```
I am confuse that why endwith method can classify the DGA domain?
Many thanks!

**Comment by pchaigno** [comment]
Thanks for your interest @csyls!

The `couldUseDomain` methods are specific to each DGA and use heuristics to indicate whether a given domain might be generated by the DGA. For example, Symmi's method encodes the fact that this DGA generates domains with a `.ddns.net` suffix and only letters in the prefix, with the exception of `j`, `y`, and `z`.
https://github.com/pchaigno/dga-collection/blob/792f3ec9c6e622993e376c8411b1184c40fafa17/dgacollection/Symmi.py#L82-L92

**Comment by Shuaiyicao** [comment]
I get it! Thank you very much!

**Comment by pchaigno** [comment]
You're most welcome!
